-- 1. USERS TABLE
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userName VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    role VARCHAR(50) NOT NULL
);

-- Index for fast login lookups
CREATE INDEX idx_users_userName ON users(userName);


-- 2. PRODUCTS TABLE
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(19, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for Search/Filter requirements
CREATE INDEX idx_products_name ON products(name);
CREATE INDEX idx_products_price ON products(price);
-- This index speeds up the default view (filtering out deleted items)
CREATE INDEX idx_products_deleted ON products(is_deleted);


-- 3. ORDERS TABLE
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    total_amount DECIMAL(19, 2) NOT NULL,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index to quickly find all orders for a specific user
CREATE INDEX idx_orders_user_id ON orders(user_id);


-- 4. ORDER ITEMS TABLE
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(19, 2) NOT NULL,
    discount_applied DECIMAL(19, 2) NOT NULL,
    total_price DECIMAL(19, 2) NOT NULL
);

-- Indexes for Joins
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_product_id ON order_items(product_id);